version: '3.8'

services:
  client:
    build:
      context: ./infrastructure/docker
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./infrastructure/docker
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/karaoke-karibu
      - REDIS_URL=redis://redis:6379

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data: